# Generated by Django 4.1.1 on 2023-06-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='document',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
