# Generated by Django 4.1.1 on 2023-07-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_store_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
