# Generated by Django 4.1.1 on 2023-07-01 10:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0003_delete_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tradingName', models.CharField(max_length=255)),
                ('ownerName', models.CharField(max_length=255)),
                ('document', models.CharField(max_length=255, unique=True)),
                ('coverageArea', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('address', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
