# Generated by Django 4.1.1 on 2023-07-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Partner',
        ),
    ]
