version: '3'
services:
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/DeliverPartners
    depends_on:
      - db
  db:
    image: postgis/postgis:13-3.1-alpine
    environment:
      POSTGRES_USER: your_postgres_username
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_db_name
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      
volumes:
  postgres_data:
